name: PetVerse CI Pipeline

on:
  push:
    branches: [ main, develop , feature/**]
  pull_request:
    branches: [ main, develop, feature/**]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

# Maven Build Ad覺mlar覺

      # Configserver
      - name: Build configserver
        working-directory: ./configserver
        run: mvn clean verify 

      - name: SonarCloud Analysis - configserver
        working-directory: ./configserver
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
           -Dsonar.projectKey=yagmurbasoglu_PetVerse \
           -Dsonar.organization=yagmurbasoglu \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
  
      # Eurekaserver
      - name: Build eurekaserver
        working-directory: ./eurekaserver
        run: mvn clean verify 
      
      - name: SonarCloud Analysis - eurekaserver
        working-directory: ./eurekaserver
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
           -Dsonar.projectKey=yagmurbasoglu_PetVerse \
           -Dsonar.organization=yagmurbasoglu \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

      # userservice        
      - name: Build userservice
        working-directory: ./userservice
        run: mvn clean verify 

      - name: SonarCloud Analysis - userservice
        working-directory: ./userservice
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
           -Dsonar.projectKey=yagmurbasoglu_PetVerse \
           -Dsonar.organization=yagmurbasoglu \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

      # activityservice
      - name: Build activityservice
        working-directory: ./activityservice
        run: mvn clean verify 

      - name: SonarCloud Analysis - activityservice
        working-directory: ./activityservice
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
           -Dsonar.projectKey=yagmurbasoglu_PetVerse \
           -Dsonar.organization=yagmurbasoglu \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

      # notificationservice
      - name: Build notificationservice
        working-directory: ./notificationservice
        run: mvn clean verify 

      - name: SonarCloud Analysis - notificationservice
        working-directory: ./notificationservice
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
           -Dsonar.projectKey=yagmurbasoglu_PetVerse \
           -Dsonar.organization=yagmurbasoglu \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml 


      # apigateway
      - name: Build apigateway
        working-directory: ./apigateway
        run: mvn clean verify 

      - name: SonarCloud Analysis - apigateway
        working-directory: ./apigateway
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
           -Dsonar.projectKey=yagmurbasoglu_PetVerse \
           -Dsonar.organization=yagmurbasoglu \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml 


      # petservice
      - name: Build petservice
        working-directory: ./petservice
        run: mvn clean verify 

      - name: SonarCloud Analysis - petservice
        working-directory: ./petservice
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
           -Dsonar.projectKey=yagmurbasoglu_PetVerse \
           -Dsonar.organization=yagmurbasoglu \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Docker Build Ad覺mlar覺
      - name: Docker build - userservice
        run: docker build -t userservice:latest ./userservice

      - name: Docker build - activityservice
        run: docker build -t activityservice:latest ./activityservice

      - name: Docker build - notificationservice
        run: docker build -t notificationservice:latest ./notificationservice

      - name: Docker build - apigateway
        run: docker build -t apigateway:latest ./apigateway

      - name: Docker build - configserver
        run: docker build -t configserver:latest ./configserver

      - name: Docker build - eurekaserver
        run: docker build -t eurekaserver:latest ./eurekaserver

      - name: Docker build - petservice
        run: docker build -t petservice:latest ./petservice

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push userservice image
        run: docker tag userservice:latest yagmurbasoglu/userservice:latest && docker push yagmurbasoglu/userservice:latest

      - name: Push activityservice image
        run: docker tag activityservice:latest yagmurbasoglu/activityservice:latest && docker push yagmurbasoglu/activityservice:latest

      - name: Push notificationservice image
        run: docker tag notificationservice:latest yagmurbasoglu/notificationservice:latest && docker push yagmurbasoglu/notificationservice:latest

      - name: Push apigateway image
        run: docker tag apigateway:latest yagmurbasoglu/apigateway:latest && docker push yagmurbasoglu/apigateway:latest

      - name: Push configserver image
        run: docker tag configserver:latest yagmurbasoglu/configserver:latest && docker push yagmurbasoglu/configserver:latest

      - name: Push eurekaserver image
        run: docker tag eurekaserver:latest yagmurbasoglu/eurekaserver:latest && docker push yagmurbasoglu/eurekaserver:latest

      - name: Push petservice image
        run: docker tag petservice:latest yagmurbasoglu/petservice:latest && docker push yagmurbasoglu/petservice:latest
     
